name: ADAF_environment
channels:
  - conda-forge
dependencies:
  #need to use slightly older version to ensure conda-forge pytorch/pytorch-gpu works
  - python=3.12 
  - pytorch
  # Use 'pytorch-gpu' to ensure the CUDA-enabled build
  - pytorch-gpu
  - torchvision
  - torchaudio
  - affine
  - asttokens
  - bokeh
  - cartopy
  - cf-xarray
  - cfgrib
  - cloudpickle
  - dask
  - dask-core
  - distributed
  - eccodes
  - esmf
  - esmpy
  - h5py
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - matplotlib
  - metpy
  - netcdf4
  - numba
  - numpy
  - pandas
  - pillow
  - pyarrow
  - pygrib
  - rasterio
  - satpy
  - scikit-learn
  - scipy
  - shapely
  - timm
  - xarray
  - xesmf
  - zarr
