#import argparse

# Standard Library
import os
import datetime as dt

# Data Science Core
import numpy as np
import pandas as pd
import xarray as xr

# Geospatial & Analysis
import xesmf
import h5py
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from scipy.spatial import KDTree
from metpy.calc import specific_humidity_from_dewpoint
from metpy.units import units

# Plotting
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib import colors
from matplotlib.markers import MarkerStyle

# Custom Packages
# from nnja_ai import DataCatalog
from funcs_modified import *

##############################################################################################################

###############################################################
#################### HRRR/RTMA FUNCTIONS ####################
###############################################################

def get_grid_alt_and_regrid(topo_filepath, ds_adaf_lats_lons, make_new_regridder=False):
    """
    Remake of get_grid_alt for the URMA native 2.5km topography
    """
    topo = xr.open_dataset(topo_filepath, engine="cfgrib", backend_kwargs={"indexpath": ""})
    topo_lon_mask = (topo.longitude>=ds_adaf_lats_lons.lon.data[0])&(topo.longitude<=ds_adaf_lats_lons.lon.data[-1])
    topo_lat_mask = (topo.latitude>=ds_adaf_lats_lons.lat.data[0])&(topo.latitude<=ds_adaf_lats_lons.lat.data[-1])
    topo = topo["orog"].where((topo_lat_mask)&(topo_lon_mask), drop=True) #'orog' valid for URMA; may need to change if using another terrain field
    if make_new_regridder:
        print(f"Making new topo regridder...")
        regridder_topo = xesmf.Regridder(topo, ds_adaf_lats_lons, 'bilinear')
        regridder_topo.to_netcdf(f"regridder_topo.nc")
    else:
        regridder_topo = xesmf.Regridder(topo, ds_adaf_lats_lons, 'bilinear', weights=f"regridder_topo.nc")

    return regridder_topo(topo, keep_attrs=True)

###################

def fetch_and_regrid_hrrr_rtma(adaf_var_str, ds_adaf_lats_lons, hrrr_filepath, rtma_filepath, make_new_regridders=False):
    """
    Reads in and fetches the appropriate HRRR and RTMA field based on the given variable string (ADAF standard naming), then regrids to the ADAF grid.
    Does the same for topography - default is the native 2.5 km terrain field from URMA. 
    Returns 2 full regridded xarray objects, one each for HRRR and RTMA of the variable requested. Further processing should happen in the calling function.
    Renames the field in the new xarray objects from the original name to the ADAF name, for convenience in the main workflow.

    Inputs:
        - adaf_var_str --> valid options = 'sp', 't', 'q', 'u10', 'v10'
        - ds_adaf_lats_lons --> xarray dataset of only ADAF lats/lons as generated by arange in main. Used for regridding
        - hrrr_filepath --> path to HRRR .grib2 file to be opened. Assumed to be a complete file, i.e. not already subset to a variable/variables
        - rtma_filepath --> path to RTMA .grib2 file to be opened. Assumed to be a complete file, i.e. not already subset to a variable/variables
        - make_new_regridders --> bool to determine if new regridders need to be built from HRRR/RTMA --> ADAF grid. Default = False. Should only be True if grid(s) change
        
    Outputs:
        xr_hrrr_regridded, xr_rtma_regridded
    """

    dict_level_selection = {"sp":{'filter_by_keys':{'stepType': 'instant', 'typeOfLevel': 'surface'}},
                            "t":{'filter_by_keys':{'typeOfLevel': 'heightAboveGround','level':2}}, 
                            "q":{'filter_by_keys':{'typeOfLevel': 'heightAboveGround','level':2}},
                            "u10":{'filter_by_keys':{'typeOfLevel': 'heightAboveGround','level':10}},
                            "v10":{'filter_by_keys':{'typeOfLevel': 'heightAboveGround','level':10}}}

    dict_adaf_translate = {'sp':'sp', 
                           't':'t2m', 
                           'q':'sh2', 
                           'u10':'u10', 
                           'v10':'v10'}

    # Load datasets and regridders (regridders should be precalculated and on disk - if not, rerun (bilinear!) )
    hrrr_backend_kwargs = dict(dict_level_selection[adaf_var_str])
    hrrr_backend_kwargs["indexpath"] = ""
    rtma_backend_kwargs = dict(dict_level_selection[adaf_var_str])
    rtma_backend_kwargs["indexpath"] = ""

    xr_hrrr = xr.open_dataset(hrrr_filepath, engine='cfgrib', backend_kwargs=hrrr_backend_kwargs)
    xr_rtma = xr.open_dataset(rtma_filepath, engine='cfgrib', backend_kwargs=rtma_backend_kwargs)

    if make_new_regridders:
        print(f"Making new HRRR and RTMA regridders...")
        regridder_hrrr = xesmf.Regridder(xr_hrrr, ds_adaf_lats_lons, 'bilinear')
        regridder_hrrr.to_netcdf(f"regridder_hrrr.nc")
        regridder_rtma = xesmf.Regridder(xr_rtma, ds_adaf_lats_lons, 'bilinear')
        regridder_rtma.to_netcdf(f"regridder_rtma.nc")
    else:
        regridder_hrrr = xesmf.Regridder(xr_hrrr, ds_adaf_lats_lons, 'bilinear', weights=f"regridder_hrrr.nc")
        regridder_rtma = xesmf.Regridder(xr_rtma, ds_adaf_lats_lons, 'bilinear', weights=f"regridder_rtma.nc")
    
    # Rename the field to the ADAF name (has to be done on the full dataset before it gets subset to a DataArray)
    xr_hrrr = xr_hrrr.rename_vars({dict_adaf_translate[adaf_var_str] : adaf_var_str})
    xr_rtma = xr_rtma.rename_vars({dict_adaf_translate[adaf_var_str] : adaf_var_str})

    # Subset down to only the variable we care about
    xr_hrrr = xr_hrrr[adaf_var_str]
    xr_rtma = xr_rtma[adaf_var_str]
    
    xr_hrrr_regridded = regridder_hrrr(xr_hrrr, keep_attrs=True)
    xr_rtma_regridded = regridder_rtma(xr_rtma, keep_attrs=True)

    return xr_hrrr_regridded, xr_rtma_regridded
    

###################
    
def fix_dataset_scaling_shifting(xr_data, adaf_var_str):
    """
    Fixes the scaling/shifting of the data of HRRR/RTMA to match ADAF. Only pressure and temperature need to be modified.
    Does NOT normalize RTMA data - that should be done after this function is run.

    Inputs:
        - xr_data --> either a HRRR or RTMA xarray dataset, resulting from fetch_and_regrid_hrrr_rtma
        - adaf_var_str --> valid options = 'sp', 't', 'q', 'u10', 'v10'
    """

    if adaf_var_str == 'sp':
        return xr_data/100 #convert Pa to hPa
    elif adaf_var_str == 't':
        xr_data = xr_data -273.15 #convert K to C
        return xr_data.where(~np.isclose(xr_data, -273.15), 0) #set all values close to -273.15 to 0
    elif adaf_var_str == 'q':
        return xr_data #no correction needed
    elif adaf_var_str == 'u10':
        return xr_data #no correction needed
    elif adaf_var_str == 'v10':
        return xr_data #no correction needed
    else:
        print(f"Invalid variable abbreviation - should only be 'sp', 't', 'q', 'u10', 'v10'")
    
###################

def min_max_norm_ignore_extreme_fill_nan_onevar_onetime(xr_data, adaf_var_str, stats_filepath):
    """
    Modified version of the min_max_norm_ignore_extreme_fill_nan function. 
    This one does only a single time (i.e. no time dimension) and a single variable, as the original code doesn't seem to work with all variables at once.

    Inputs:
        - xr_data --> HRRR or RTMA data that has been run through fetch_and_regrid_hrrr_rtma and fix_dataset_scaling_shifting. Should be 2D
        - adaf_var_str --> string to select the right variable's stats. MUST BE MODIFIED BEFOREHAND, e.g. "rtma_sp" instead of just "sp"
        - stats_filepath --> str of filepath to the stats.csv file containing variable min/max values
    """

    stats = pd.read_csv(stats_filepath, index_col=0)
    field_tar_stats = stats.loc[stats['variable'] == adaf_var_str]

    #Loop version of the ndim code
    vmin = field_tar_stats["min"]
    vmax = field_tar_stats["max"]
    vmin = np.array(vmin)
    vmax = np.array(vmax)
    
    for j in range(xr_data.ndim-1):
        vmin = vmin[:, np.newaxis]
        vmax = vmax[:, np.newaxis]
    
    for j in range(xr_data.ndim): #no temporal dimension yet - if that gets included as dim 0, then this should only apply to dims 1,2,..,n
        vmin = np.repeat(vmin, xr_data.shape[j], axis=j)
        vmax = np.repeat(vmax, xr_data.shape[j], axis=j) 

    xr_data -= vmin
    xr_data *= 2.0/(vmax-vmin)
    xr_data -= 1.0

    #Mask out-of-range values; xr.where is a little odd for replacing values
    xr_data = xr_data.where(xr_data <= 1, other=1)
    xr_data = xr_data.where(xr_data >= -1, other=-1)

    xr_data = xr_data.fillna(0) 

    return xr_data


###############################################################
#################### STATION OBS FUNCTIONS ####################
###############################################################

def get_nnja_metar_dataframe(analysis_time, list_of_metar_vars, time_period=14, catalog_str='conv-adpsfc-NC000007'):
    """
    Finds and loads the appropriate METAR data from NNJA-AI into a dataframe.
    Loads all variables from list_of_metar_vars (which should include "LAT", "LON", and "OBS_TIMESTAMP")
    Restricts the data to a time range of [analysis_time-1, analysis_time+time_period-1] days. Default = 2 weeks (14 days)
    """
    catalog = DataCatalog(mirror="gcp_brightband")
    dataset = catalog[catalog_str]
    dataset_subset = dataset.sel(time=slice((analysis_time-dt.timedelta(days=1)).strftime("%Y-%m-%d"), 
                                            (analysis_time+dt.timedelta(days=time_period-1)).strftime("%Y-%m-%d")),
                                 variables=list_of_metar_vars) 
    df_master = dataset_subset.load_dataset(backend="pandas")

    return df_master

###################

def check_nnja_metar_dataframe(df_master, analysis_time, list_of_metar_vars, obs_time_window=3, time_period=7, catalog_str='conv-adpsfc-NC000007'):
    """
    Checks if the requested interval [analysis_time - obs_time_window, analysis_time] is fully covered by the existing df_master. 
    If any part of that window falls outside the current df_master range, a new dataframe is loaded.
    """
    start_time = analysis_time - dt.timedelta(hours=obs_time_window)

    df_times = df_master['OBS_TIMESTAMP'].dt.tz_localize(None).dt.floor('h')
    df_min = df_times.min()
    df_max = df_times.max()

    # Check if the required window is outside the current range
    # If the window starts earlier than our min, or ends later than our max, we need a reload
    if (start_time < df_min) or (analysis_time > df_max):
        print(f"Requested window [{start_time} to {analysis_time}] falls outside current coverage [{df_min} to {df_max}]. Loading new data...")
        
        df_master = get_nnja_metar_dataframe(analysis_time, 
                                             list_of_metar_vars, 
                                             time_period=time_period, 
                                             catalog_str=catalog_str)
        
    return df_master

###################

def get_missing_obs_hours(df_master, analysis_time, obs_time_window=3, time_col='OBS_TIMESTAMP'):
    """
    Returns the list of required hourly timestamps that are missing from df_master for a given analysis time.
    Required hours are [analysis_time-(obs_time_window-1), ..., analysis_time].
    """
    if time_col not in df_master.columns:
        return list(pd.date_range(end=analysis_time, periods=obs_time_window, freq='h').to_pydatetime())

    # Coerce to UTC to handle both naive and tz-aware timestamps consistently.
    obs_times = pd.to_datetime(df_master[time_col], errors='coerce', utc=True)
    obs_times = obs_times.dropna().dt.tz_convert(None).dt.floor('h')
    available_hours = set(obs_times.unique().tolist())

    required_hours = pd.date_range(end=analysis_time, periods=obs_time_window, freq='h')
    missing_hours = [ts.to_pydatetime() for ts in required_hours if ts not in available_hours]

    return missing_hours
    
###################

def select_and_clean_metar_obs(df_master, analysis_time, obs_time_window, drop_nans=True, convert_units=True, rename_data_vars=True):
    """
    Subselects a known good (in terms of time range) df_master down to the needed time window, and performs data cleanup.
    
    - If drop_nans=True (default), all rows with at least one NaN observation are dropped.
    - If convert_units=True (default), temperature and pressure are changed (K-->C and Pa-->hPa respectively)
    - If rename_data_vars=True (default), temperature and pressure get renamed to 'sta_t' and 'sta_p'.
        Note: LAT and LON are always renamed to lat and lon here
    """
    time_sel_str_start = (analysis_time-dt.timedelta(hours=obs_time_window)+dt.timedelta(seconds=1)).strftime("%Y-%m-%d %H:%M:%S") #start is delayed. Addition of 1 second is needed to cull some weird stragglers that get rounded up to t-3 which we don't want
    time_sel_str_end = analysis_time.strftime("%Y-%m-%d %H:%M:%S") 

    df = df_master[df_master['OBS_TIMESTAMP'].between(time_sel_str_start, time_sel_str_end)] #filter to only obs_window times
    
    df.rename(columns={"LAT": "lat", "LON": "lon"}, inplace=True)
    
    if drop_nans: # QC to drop any points where any of the vars are NaN (or coords, though in practice this never happens)
        df = df.dropna()
    if convert_units:
        df["MTRPRS.ALSE"] = df["MTRPRS.ALSE"]*0.01 #Pa to hPa 
        df["MTRTMP.TMDB"] = df["MTRTMP.TMDB"]-273.15 #K to C. Don't have to worry about dewpoint temp as that gets overwritten
    if rename_data_vars:
        df.rename(columns={"MTRTMP.TMDB": "sta_t", "MTRPRS.ALSE": "sta_p"}, inplace=True) #the other vars are yet to be calculated and are renamed in those functions

    return df
    
###################

def assemble_complete_metar_df(df_master, analysis_time, obs_time_window, df_adaf_lats_lons,
                               adaf_lat_min=24.675, adaf_lat_max=50.275, 
                               adaf_lon_min=231.975, adaf_lon_max=295.975,
                               threshold_mins=30, max_dist_km=10):
    """
    Assembles a complete dataframe of processed, filtered, etc METAR data.
    df_master should be known good (i.e. has all necessary times).
    """

    df = select_and_clean_metar_obs(df_master, analysis_time, obs_time_window, 
                                    drop_nans=True, convert_units=True, rename_data_vars=True)
    df = assign_closest_with_threshold(df, df_adaf_lats_lons, 
                                       lat_min=adaf_lat_min, lat_max=adaf_lat_max, 
                                       lon_min=adaf_lon_min, lon_max=adaf_lon_max, 
                                       max_dist_km=max_dist_km)
    df = keep_closest_to_hour_per_location_with_time_threshold(df, threshold_mins=threshold_mins, past_obs_only=True)
    df['OBS_TIMESTAMP'] = df['OBS_TIMESTAMP'].dt.ceil('h')
    df = filter_obs_by_temporal_completeness(df, obs_time_window=obs_time_window)
    df = convert_wind_to_uv(df)
    df = add_specific_humidity(df)
    df = reject_out_of_bounds_obs(df)

    return df
    
###################

def assign_closest_with_threshold(df_target, df_ref, lat_min, lat_max, lon_min, lon_max, 
                                  max_dist_km=None, lat_col='lat', lon_col='lon'):
    """
    Filters coordinates and assigns the closest reference point, 
    rejecting assignments that exceed max_dist_km.

    Inputs:
        - df_target --> dataframe from NNJA-AI, already cut down to the hours of interest
        - df_ref --> dataframe constructed from ADAF lat/lons
        - lat/lon min/max --> USA bounds from ADAF work (should be lat_min=24.675, lat_max=50.275, lon_min=231.975, lon_max=295.975)
        - max_dist_km --> should be 10 
    """

    #Get datasets onto common lat/lon convention, if they differ
    def normalize(df): 
        temp_df = df.copy()
        temp_df[lon_col] = temp_df[lon_col] % 360
        return temp_df

    # Normalize and Filter Dataframes
    df_t_norm = normalize(df_target)
    df_r_norm = normalize(df_ref)

    t_mask = (df_t_norm[lat_col].between(lat_min, lat_max)) & \
             (df_t_norm[lon_col].between(lon_min, lon_max))
    r_mask = (df_r_norm[lat_col].between(lat_min, lat_max)) & \
             (df_r_norm[lon_col].between(lon_min, lon_max))

    df_t_filtered = df_t_norm[t_mask].copy()
    df_r_filtered = df_r_norm[r_mask].drop_duplicates(subset=[lat_col, lon_col])

    if df_t_filtered.empty or df_r_filtered.empty:
        return pd.DataFrame(columns=df_target.columns)

    # Build KDTree and Query
    ref_coords = df_r_filtered[[lat_col, lon_col]].values
    tree = KDTree(ref_coords)
    
    target_coords = df_t_filtered[[lat_col, lon_col]].values
    distances, indices = tree.query(target_coords)

    # Apply Distance Threshold (if provided)
    if max_dist_km is not None:
        # Convert km to approximate decimal degrees
        # 111 km per degree is fine for our purposes
        max_dist_degrees = max_dist_km / 111.0
        
        # Keep only rows where the closest point is within the threshold
        valid_mask = distances <= max_dist_degrees
        df_t_filtered = df_t_filtered[valid_mask]
        indices = indices[valid_mask]
        
        if df_t_filtered.empty:
            return df_t_filtered

    # Overwrite with closest reference coordinates
    closest_matches = ref_coords[indices]
    df_t_filtered[lat_col] = closest_matches[:, 0]
    df_t_filtered[lon_col] = closest_matches[:, 1]

    return df_t_filtered
    
###################

def keep_closest_to_hour_per_location_with_time_threshold(df_input, time_col='OBS_TIMESTAMP', lat_col='lat', lon_col='lon', threshold_mins=30, past_obs_only=True):
    """
    Filters a DataFrame to keep the point closest to each hour, 
    calculated independently for each unique geographic coordinate.

    If past_obs_only=True (default) then only observations from BEFORE each hour will be considered. If False, then observations after the top of the hour will also be considered.
    Returns a dataframe with OBS_TIMESTAMP not yet rounded (or ceilinged) to the nearest hour - that behavior is up to the calling function.
    
    Should be applied to a dataframe that has already undergone regridding (i.e. the output of assign_closest_with_threshold() )
    """
    df = df_input.copy() #.copy() isn't a true deepcopy, but probably fine for this; if not, use copy.deepcopy(df_input)
    
    ## Create the rounding target
    if past_obs_only:
        df['target_hour'] = df[time_col].dt.ceil('h') 
    else:
        df['target_hour'] = df[time_col].dt.round('h') 

    ## Calculate absolute difference from that hour
    df['time_diff'] = (df[time_col] - df['target_hour']).abs() #if using ceiling, then absolute difference doesn't matter, but it does if using .round so no harm in keeping it around

    ## Only keep rows where the difference is <= the specified minutes
    max_delta = pd.Timedelta(minutes=threshold_mins)
    df = df[df['time_diff'] <= max_delta]

    ## Sort by coordinates, the target hour, and then the time difference
    ## This puts the "closest" record at the top of each (Location + Hour) group
    df_filtered = df.sort_values(by=[lat_col, lon_col, 'target_hour', 'time_diff']).drop_duplicates(subset=[lat_col, lon_col, 'target_hour'], keep='first')

    #Clean up helper columns
    return df_filtered.drop(columns=['target_hour', 'time_diff']).sort_values(by=[time_col, lat_col])
    
###################

def filter_obs_by_temporal_completeness(df_input, obs_time_window, precision=4):
    """
    Checks if each (lat, lon) point has a row for every hour in the window.
    Points missing any hour are removed entirely.
    """
    # 1. Work on a copy to ensure we don't modify the input df directly
    df = df_input.copy()
    
    # 2. Round coordinates to prevent precision-related grouping errors
    df[['lat', 'lon']] = df[['lat', 'lon']].round(precision)
    
    # 3. Count unique timestamps for each coordinate pair
    # transform('nunique') assigns the total count of unique hours to every row in that group
    counts = df.groupby(['lat', 'lon'])['OBS_TIMESTAMP'].transform('nunique')
    
    # 4. Keep only the points where the count matches the required window size
    # If a point has 4 UTC and 6 UTC but is missing 5 UTC, its count will be 2.
    # Since 2 != 3 (if window is 3), those rows will be dropped.
    df_filtered = df[counts == obs_time_window]
    
    return df_filtered
    
###################

def convert_wind_to_uv(df_input, speed_col='MTRWND.WSPD', dir_col='MTRWND.WDIR', tolerance=1e-6):
    """
    Converts wind speed and direction to U and V components, overwriting the original columns in the process.
    """
    
    df = df_input.copy()
    
    # Convert direction to radians
    rad = np.deg2rad(df[dir_col])
    
    # Calculate U and V components
    # Store them in temporary variables first to avoid using the overwritten speed_col for the second calculation
    u = -df[speed_col] * np.sin(rad)
    v = -df[speed_col] * np.cos(rad)

    # Round tiny values to 0
    u[u.abs()<tolerance] = 0
    v[v.abs()<tolerance] = 0
    
    # Overwrite the original columns
    df[speed_col] = u
    df[dir_col] = v
    
    # Rename columns to reflect the new data
    df.rename(columns={speed_col: 'sta_u10', dir_col: 'sta_v10'}, inplace=True)
    
    return df
    
###################

def add_specific_humidity(df_input, dewpoint_col='MTRTMP.TMDP', pressure_col='sta_p'):
    """
    Calculates specific humidity from dewpoint (in Kelvin) and pressure. Pressure needs to have already been converted from Pa (native) to hPa.
    """
    df = df_input.copy()
    
    dp_k = df[dewpoint_col].values * units.K
    p_hpa = df[pressure_col].values * units.hPa
    
    sh_quantity = specific_humidity_from_dewpoint(p_hpa, dp_k)

    df[dewpoint_col] = sh_quantity.to('kg/kg').m
    df.rename(columns={dewpoint_col: 'sta_q'}, inplace=True)
    
    return df
    
###################

def reject_out_of_bounds_obs(df_input, dict_var_ranges=None):
    """
    Performs QC, removing all points where t, q, u10, or v10 is outside the acceptable range.
    """
    df = df_input.copy()

    if dict_var_ranges is None:
        dict_var_ranges = {'sta_t':(-40,50),
                           'sta_q':(0, 0.025), #note this is in kg/kg, not g/kg
                           'sta_u10':(-25,25),
                           'sta_v10':(-25,25)
                          }
    
    for col, (min_val, max_val) in dict_var_ranges.items():
        if col in df.columns:
            # .between() is inclusive by default (both min and max are kept)
            df = df[df[col].between(min_val, max_val)]
        else:
            print(f"Warning: Column '{col}' not found in DataFrame. Skipping.")
            
    return df
    
###################

def min_max_norm_ignore_extreme_fill_nan_sta_df(df_input, stats_path='stats.csv'):

    df = df_input.copy()
    
    stats = pd.read_csv(stats_path)
    stats = stats.set_index('variable')

    target_cols = ['sta_t', 'sta_q', 'sta_p', 'sta_u10', 'sta_v10']
    
    for col in target_cols:
        # Only process if the column exists in both the dataframe and the stats file
        if col in df.columns and col in stats.index:
            vmin = stats.loc[col, 'min']
            vmax = stats.loc[col, 'max']

            df[col] -= vmin
            df[col] *= 2.0 / (vmax - vmin)
            df[col] -= 1.0
            
            df[col] = np.where(df[col] > 1, 1, df[col])
            df[col] = np.where(df[col] < -1, -1, df[col])
            df[col] = np.nan_to_num(df[col], nan=0.0)
            
    return df
    
###################

def create_obs_xarray(df_obs, df_coords, analysis_time, time_col='OBS_TIMESTAMP', lat_col='lat', lon_col='lon'):
    """
    Converts binned observations and a coordinate list into a single 3D xarray object.
    
    Coordinates:
    - obs_time_window: 0 (t-2), 1 (t-1), 2 (t)
    - latitude: from df_coords
    - longitude: from df_coords
    """
    # 1. Map timestamps to the window index (0, 1, 2)
    # Sorted order ensures the oldest time is 0 and newest is 2
    unique_times = sorted(df_obs[time_col].unique())
    time_map = {t: i for i, t in enumerate(unique_times)}
    
    df_prepared = df_obs.copy()
    
    # --- PRECISION CHECK: Round observations to 4 decimal places ---
    df_prepared[[lat_col, lon_col]] = df_prepared[[lat_col, lon_col]].round(4)
    
    df_prepared['obs_time_window'] = df_prepared[time_col].map(time_map)
    
    # 2. Set MultiIndex for the transition to xarray
    # We drop the original time column to keep the data variables clean
    df_prepared = df_prepared.drop(columns=[time_col]).set_index(['obs_time_window', lat_col, lon_col])
    
    # 3. Convert to xarray Dataset
    ds = df_prepared.to_xarray()
    
    # 4. Enforce the master coordinate list from df_coords
    # This ensures the Dataset contains all locations, filling missing ones with NaN
    # --- PRECISION CHECK: Round master coordinates to 4 decimal places ---
    master_lats = sorted(df_coords[lat_col].round(4).unique())
    master_lons = sorted(df_coords[lon_col].round(4).unique())
    
    ds = ds.reindex({
        lat_col: master_lats,
        lon_col: master_lons
    })
    
    # 5. Add standard metadata
    ds[lat_col].attrs = {'units': 'degrees_north'}
    ds[lon_col].attrs = {'units': 'degrees_east'}

    # 6. Add obs_mask and valid_time(=analysis_time), and make all NaNs 0
    valid_time_ns = np.datetime64(analysis_time, 'ns')
    ds_final = (
        ds.assign(
            obs_mask=(
                ds.to_array()
                .notnull()
                .all(dim="variable")           # True if all vars present at this point (sanity check - should already have been handled at the start by get_nnja_metar_data with drop_nans=True)
                .all(dim="obs_time_window")    # True if present across the whole window (sanity check - should already have been handled by filter_obs_by_temporal_completeness)
                .astype(int)                   # Final 2D binary mask (lat, lon)
            )
        )
        .fillna(0)                             # Replace NaNs with 0 in all data variables
        .assign_coords(valid_time=valid_time_ns) # To match ADAF example
    )
    
    return ds_final

###################

def reverse_norm_xr(xr_ds, var_name, stats_path=f"/scratch3/BMC/wrfruc/aschein/ADAF/data_preparation_new/stats.csv"):
    """
    Undoes the min-max norm for normalized data.
    Only for xarray datasets at the moment.
    Assumes the zeros at non-station locations have been removed.

    var_name = one of 'sta_t', 'sta_q', 'sta_p', 'sta_u10', 'sta_v10'
    """
    xr_ds_tmp = xr_ds.copy()
    
    data = xr_ds_tmp[var_name].data
    stats = pd.read_csv(stats_path)
    stats = stats.set_index('variable')
    
    vmin = stats.loc[var_name, 'min']
    vmax = stats.loc[var_name, 'max']

    data = (data + 1) * (vmax - vmin) / 2 + vmin

    xr_ds_tmp[var_name].data = data
    
    return xr_ds_tmp
    

###########################################################
#################### MESONET FUNCTIONS ####################
###########################################################

def load_mesonet_into_dataframe_and_clean(path, 
                                          ADAF_CHANNELS=None, 
                                          GOOD_QM=None, 
                                          QM_FILLVALUE=None, 
                                          FLOAT_FILLVALUE=None,
                                          LAT_BOUNDS=(24.0,50,0),
                                          LON_BOUNDS=(235.0, 293.0),
                                          drop_qm_cols=True):
    """
    Function to load Mesonet data (in IODA standard) from disk and turn it into a cleaned-up pandas Dataframe.
    """
    # Enforce that the user must explicitly pass all configuration values
    if (ADAF_CHANNELS is None or GOOD_QM is None or QM_FILLVALUE is None or FLOAT_FILLVALUE is None):
        raise ValueError("Missing required arguments. You must explicitly provide: ADAF_CHANNELS, GOOD_QM, QM_FILLVALUE, and FLOAT_FILLVALUE.")

    d = {}
    
    with h5py.File(path, "r") as f:
        d["lat"] = f["MetaData/latitude"][:]
        d["lon"] = f["MetaData/longitude"][:]
        
        # Convert timestamps to datetime objects immediately
        d["OBS_TIMESTAMP"] = pd.to_datetime(f["MetaData/dateTime"][:], unit='s', origin='unix', errors='coerce')
        
        for v in ADAF_CHANNELS:
            d[v] = f[f"ObsValue/{v}"][:].astype("float64")
            qmkey = f"QualityMarker/{v}"
            d[v + "_qm"] = f[qmkey][:] if qmkey in f else np.full(d[v].shape, QM_FILLVALUE, dtype="int32") # Fallback array if QM doesn't exist

    # Load into a DataFrame for vectorized row operations
    df = pd.DataFrame(d)
    
    # Geographic Bounding Box Filter (Applied early to optimize groupby performance)
    df = df[(df["lat"] >= LAT_BOUNDS[0]) & (df["lat"] <= LAT_BOUNDS[1])]
    df = df[(df["lon"] >= LON_BOUNDS[0]) & (df["lon"] <= LON_BOUNDS[1])]
    
    # Mask all fill values to NaN so the merge process can identify valid data
    for v in ADAF_CHANNELS:
        df[v] = df[v].mask(df[v] > FLOAT_FILLVALUE, np.nan)
        df[v + "_qm"] = df[v + "_qm"].replace(QM_FILLVALUE, np.nan)
        
    # Merge the split station rows
    # groupby().first() combines rows matching on lat/lon/time, choosing the first non-NaN element
    df_merged = df.groupby(["lat", "lon", "OBS_TIMESTAMP"], as_index=False, dropna=False).first()
    
    #Rename columns to the new schema and define qm_cols early
    rename_dict = {}
    for long_name, short_name in ADAF_CHANNELS.items():
        rename_dict[long_name] = f"sta_{short_name}"
        rename_dict[f"{long_name}_qm"] = f"sta_{short_name}_qm"
        
    df_merged = df_merged.rename(columns=rename_dict)
    
    # Filter out rows with bad Quality Markers
    # Keeps rows if the QM is in GOOD_QM; if the QM is NaN (meaning that variable wasn't recorded) it's dropped
    qm_cols = [x for x in rename_dict.values() if "_qm" in x]
    valid_qm_mask = df_merged[qm_cols].isin(GOOD_QM)
    df_clean = df_merged[valid_qm_mask.all(axis=1)]

    # Handle Quality Marker columns based on user preference
    if drop_qm_cols:
        df_clean = df_clean.drop(columns=qm_cols)
    else:
        df_clean[qm_cols] = df_clean[qm_cols].astype("Int32") #Convert quality marker columns back to ints+NaNs allowed ("Int32")
    
    # Clean up the index and return the final DataFrame
    return df_clean.reset_index(drop=True)
    
    
#################################################################
#################### MISCELLANEOUS FUNCTIONS ####################
#################################################################

def plot_data(xr_dataset, title_str="TITLE", thinning=2):
    extent = [-130, -63, 22, 54] #USA
    projection = ccrs.PlateCarree()
    
    fig, ax = plt.subplots(1,1, figsize=(14,9), subplot_kw={'projection':projection})
    
    ax.set_extent(extent, crs=projection)
    ax.add_feature(cfeature.STATES.with_scale('50m'), linewidth=0.4)
    ax.add_feature(cfeature.COASTLINE.with_scale('50m'), linewidth=0.3)

    X, Y = np.meshgrid(xr_dataset.lon, xr_dataset.lat)
    
    im = ax.scatter(X[::thinning], Y[::thinning], c=xr_dataset.data[::thinning], s=0.2, cmap='coolwarm') 
    plt.colorbar(im, shrink=0.4, pad=0.01)

    plt.title(title_str)